# Generated by Django 3.0 on 2022-10-11 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0002_auto_20221007_1622'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table=None,
        ),
        migrations.AlterModelTable(
            name='letting',
            table=None,
        ),
    ]
