version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: Install pip packages
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Test with pytest
          command: |
            . venv/bin/activate
            pytest
      - run:
          name: run linting and metrics
          command: |
            . venv/bin/activate
            flake8
  containerize:
    docker:
      - image: cimg/base:2022.06
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build and push to Docker Hub
          command: |
            IMAGE_TAG="${CIRCLE_SHA1}"
            docker build -t $DOCKER_HUB_USER_ID/$IMAGE_NAME:$IMAGE_TAG .
            echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER_ID" --password-stdin
            docker push $DOCKER_HUB_USER_ID/$IMAGE_NAME:$IMAGE_TAG

workflows:
  version: 2
  build-master:
    jobs:
      - build
      - containerize:
          filters:
            branches:
              only: master
          requires:
            - build


