# Generated by Django 3.0 on 2022-10-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20221007_1539'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
